### ISSUE TITLE
Option to finish smart fill instantly

### ISSUE THREAD

**Issue by Splits285** [chsh2/nijiGPen#46]
I like the fill hints tool but I find it hard to work with fills when I don't know what their final result is going to be, and reaching for the enter key to confirm can be taxing on the hand. I attempted to program this in myself, but self.smart_fill_finalize() being run too quickly doesn't let anything get drawn. I can't figure out what to look for to be sure that the fill was drawn before finishing the modal.

Having seen how blender refuses to give useful finish signals to operators I'm not even ready to believe it's possible. If it isn't, that's ok.

**Comment by chsh2** [comment]
Yes I think I can add an option to switch between the interactive mode and single-click mode.

And maybe in addition to the Enter key, the middle mouse button can be used for confirmation? So that interactive filling can be done with the mouse only.

**Comment by Splits285** [comment]
Perhaps allowing any button to bind would work best, I use mouse4 to erase because of a special configuration I have on my pen.

**Comment by chsh2** [comment]
I added an option to finish filling after a single click. But from my personal experience, it often does not give a perfect result without more hints made by user.

For the interactive mode, it might be difficult to allow arbitrary key bindings, because detecting Blender keymaps during a modal is tricky. Currently, I limit the binding to mouse buttons only. Later I may investigate if there is a better solution.
![1](https://github.com/user-attachments/assets/c670a3b8-cabe-4a41-815b-3bea9984e5a2)

I also try to render clickable buttons on the screen for a better touchscreen control.
![2](https://github.com/user-attachments/assets/ef1ded44-aee3-434a-8738-dc64e80d39d1)

**Comment by Splits285** [comment]
Thanks so much man, you're a god.
