### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by tugok** [chsh2/nijiGPen#9]
Whatever I do I cannot install the necessary dependencies inside the addon preferences.
I've tried clicking the buttons and refreshing, clicking the buttons and reopening blender, using different blender versions (3.4 and 3.3.2 LTS) and no luck

I've also tried using the python method but copying pasting the code got me an "invalid syntax" error. Can you help me?

**Comment by tugok** [comment]
Also tried different versions of your addon (0.2.2 and 0.2.1). I can try another ones

**Comment by b4zz4** [comment]
This not work?

![2022-12-08-110239_498x422_scrot](https://user-images.githubusercontent.com/643833/206464839-79dbe083-63bc-4c11-91a1-a0a14308b67f.png)

**Comment by b4zz4** [comment]
Operative system
If it's linux what distribution and repository/package?

**Comment by chsh2** [comment]
Does the console ( [Window] - [Toggle System Console] ) show any information after clicking the install button?

**Comment by tugok** [comment]
> What operating system do you have? If it's linux what distribution and repository/package?

Windows 10 Pro

**Comment by tugok** [comment]
> Does the console ( [Window] - [Toggle System Console] ) show any information after clicking the install button?

Yes, this 
![image](https://user-images.githubusercontent.com/120107894/206533057-2d024cd4-f9f9-428c-8d6e-017820341655.png)

**Comment by chsh2** [comment]
> Yes, this ![image](https://user-images.githubusercontent.com/120107894/206533057-2d024cd4-f9f9-428c-8d6e-017820341655.png)

Thank you. I did not consider the case of the Microsoft Store version of Blender. In this case, the add-on is not permitted to write files in the Blender folder. Although it shows the installation is successful, the dependencies are actually installed somewhere else and cannot be used by Blender.

I will keep an eye on this issue, but currently there is no solution. Add-ons by other authors which need dependencies seem to suffer from this problem too. You may consider install Blender in another way, such as the portable version.

**Comment by tugok** [comment]
Thank you, I downloaded blender 3.4 from the website and installed it. Still the same issue tho :(

**Comment by chsh2** [comment]
What is the installation folder? And does it have the same issue when running Blender as administrator?

**Comment by tugok** [comment]
C:\Program Files\Blender Foundation\Blender 3.4 and yes, i do

**Comment by chsh2** [comment]
Maybe the previous installation attempts messed up the configuration. I tried to imitate your environment, and solved this issue by using the command line. The commands I use are (as administrator):
![image](https://user-images.githubusercontent.com/110356534/206555122-6dd12caf-d047-419c-b245-cdbe09c9d6c1.png)
But I do not know if it works for you as well.

The dependency installation of Blender is very tricky. Maybe you can also refer to this add-on:
https://github.com/cgtinker/BlendArMocap/issues
It also uses dependencies and has collected many related issues and solutions. Some of them can also be applied here.

**Comment by tugok** [comment]
> Maybe the previous installation attempts messed up the configuration. I tried to imitate your environment, and solved this issue by using the command line. The commands I use are (as administrator): ![image](https://user-images.githubusercontent.com/110356534/206555122-6dd12caf-d047-419c-b245-cdbe09c9d6c1.png) But I do not know if it works for you as well.
> 
> The dependency installation of Blender is very tricky. Maybe you can also refer to this add-on: https://github.com/cgtinker/BlendArMocap/issues It also uses dependencies and has collected many related issues and solutions. Some of them can also be applied here.

YES! That worked! Both pyclipper and triangle are now marked as OK. However Scikit-Image (the optional one) is still marked as "not installed" Can you give me instructions on this as well?

**Comment by chsh2** [comment]
> Please can you do step by step video in your youtube channel to insall pyclipper triangle and scikit imagei am not into coding.thanks in advance i am using blender 3.4

In most cases, the buttons in the preference panel will work. However, once it does not work, things will get tricky, because there are many possible reasons, depends on your operating system, the folder where Blender is installed and network conditions. Can you please share these information, or the log in the Blender's console? I may make such a tutorial video in the future, but now I have not gathered enough data and therefore need your help.

> YES! That worked! Both pyclipper and triangle are now marked as OK. However Scikit-Image (the optional one) is still marked as "not installed" Can you give me instructions on this as well?

I cannot reproduce this problem, therefore I do not guarantee my solution will work:
A straightforward way to check this issue may be to reinstall Blender and install the dependencies as administrator before any other attempts. (Do not try to install them without administrator permission.)

Another method is to try following commands:
`python.exe -m pip uninstall scipy`
then,
`python.exe -m pip install scikit-image`
If this does not work, please share the outputs of these commands.

By the way, currently `scikit-image` is only used for line art extraction. You can ignore it if you only care about other functions. In the future, the sketch clean-up may need it, but I haven't finished this function yet.

**Comment by Ramamoorthi1985** [comment]
> 
what is command line instruction sir? how to do it can you share step by step video or instruction?pls help.I dont have any coding experience

**Comment by chsh2** [comment]
> That command method did not work, although it seemed to have installed correctly, as you can see here. Maybe i did something wrong?
> 
> <img alt="image" width="796" src="https://user-images.githubusercontent.com/120107894/207390425-69308de6-17fa-48d1-a0dc-086aa7184021.png">

It still does not look quite correct. Normally the addon or pip should only write files to the Blender folder, but now the packages are installed to the user appdata folder, which cannot be called by Blender.

If you find any of the following files in `c:\users\...\appdata\roaming\python\python310\site-packages`, maybe you can manually copy them to `c:\program files\blender foundation\blender 3.4\3.4\python\lib\site-packages` (do not overwrite if the files are already in Blender's folder) to see if they can be detected?
![dependencies](https://user-images.githubusercontent.com/110356534/207760638-6cb80dea-0fab-4d3d-81ed-538479d58f21.png)

Installing/extracting Blender in a non-system folder may also help, since the administrator permission will not be required.

**Comment by tugok** [comment]
Hey! Sorry I didnt see your message. Yes, that last trick worked! Thank you so much! Cant wait to try your new cleaning line tool!
